### ISSUE TITLE
change title

### ISSUE THREAD

**Issue by tch1001** [TwigSlot/twig-client#50]
the title is currently just TWIG, change it to update with the page the user is at
- for explore, "Explore"
- for project, project title
  - indicate project title in the navbar, maybe make it editable (refer to EditProject.vue)
- for user, user first name + last name

**Comment by Alien10123** [comment]
Can I work on this? I want to contribute to some open source projects and this seems like a good issue for me.

**Comment by tch1001** [comment]
@Alien10123 yes please! You can contact me on telegram (tch1001) if u need further guidance :) ie for setup

**Comment by Alien10123** [comment]
Thanks. Working on it now.

**Comment by Alien10123** [comment]
HI @tch1001, I am having trouble setting up the login locally, and I don't have telegram so is there any other way top contact you?
Thanks

**Comment by tch1001** [comment]
@Alien10123 you can check out twig-server README first. I will open a discussion there for setting up the dev server and you can ask questions there!

**Comment by Alien10123** [comment]
I finished it. https://github.com/TwigSlot/twig-client/pull/51. Also I followed the readme but either the code wasn't working or my docker wasn't working. I don't know much python or docker (I have used both a bit) so I didn't try to fix it.

**Comment by tch1001** [comment]
Thanks! @Alien10123 do take a look at other issues if u wish :)))

**Comment by Alien10123** [comment]
I expected that, but I mainly use svelte and astro so I don't really know all the things about vue router and such. Thanks for telling me.
